### ISSUE TITLE
Label wraps text in component table

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#161] opened 2021-07-19 14:18 UTC
In a specific screen, the label reports its size not correctly and wraps. Check internal ticketing for more info

**Comment by gimmixAT** [comment] 2021-07-23 14:47
this is probably also fixed by https://github.com/sibvisions/reactUI/commit/466fdae3203575d34fdad70ce2c6b0721e666d0c

There was a similar break issue in the internal test app with numbered labels which is also gone and was caused by the browser internal floor on the width.

**Closed** 2021-07-26 06:05 UTC
Labels: internal ticketing
