### ISSUE TITLE
Table scrolling totally wrong

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#473] opened 2024-04-16 09:31 UTC
branch: master_04_03_2024

User: features
Screen: Lazy loading

Scroll down without touching the scrollbar, just by mouse wheel

If table re-fetches records, the shown record is wrong and the table flickrs. The big problem is that you scroll to record 600 and see record 450?

Second: If you scroll down by touching the scrollbar handle -> the records are not shown and the whole scroll area is white, until you scroll up?

And if all records are fetched, it's possible to continue scrolling.

So, current table implementation with fetch-on-demand is not working!

I guess we have the same problem in master branch with latest primereact? but I know that the table acts different in latest primereact.

**Comment by gimmixAT** [comment] 2024-04-16 20:51
I was able to reproduce it in the master_04_03_2024 branch so I'll look into ways to maybe fix it.
On the master branch though this doesn't seem to happen for me, so I'll also check if things changed besides the updated primereact version.

**Comment by gimmixAT** [comment] 2024-04-17 19:58
The skipping seems to not happen if we don't set the loading flag on the virtual scroller settings.

@rjahn try removing `loading: listLoading` in UITable.tsx:1542

**Comment by rjahn** [comment] 2024-04-19 08:21
Tried it out and looks good (my line number was: 1539?)

But the scrollbar still has the problem if you press the handle and move down. The amount is just wrong and a white table appears (no records)...

**Comment by gimmixAT** [comment] 2024-04-22 11:05
in which browser are you testing it currently? In FF it does have some white flicker for me at the bottom but also works by dragging the scrollbar manually

**Comment by rjahn** [comment] 2024-04-22 11:58
Chrome 123.0.6312.107 (official build) (arm64)

It's different with Safari: Can't move the scroll handle because it's not shown

**Comment by rjahn** [comment] 2024-09-16 12:05
No scroll bar in Safari - I guess this is correct?

Scroll bar flickr in Firefox, but works
No problems in Chrome and works

I guess scrolling to the last record wasn't tested because the table has 300.000 records. I tried to scroll down 13.000 records and didn't have a white area in FF or Chrome.

**Comment by gimmixAT** [comment] 2024-11-21 15:53
I just tried validating this on macOS, since I think that is where you do most of the testing @rjahn. Safari seems to be working fine -> scrollbar is only visible while scrolling which is the default macOS behavior.

**Comment by gimmixAT** [comment] 2024-11-21 16:54
the flickering in FF should be fixed now

**Closed** 2024-11-25 11:38 UTC
Labels: bug, Priority, critical
