### ISSUE TITLE
Focus cut off?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#452] opened 2024-03-06 11:35 UTC
Do we set overflow: false for panels?

The focus is not fully visible:

<img width="421" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/ff59bed6-5e42-4ce5-8eab-7da3eeddb4e7">

**Comment by maximilianweidenauer** [comment] 2024-03-08 11:25
Yes overflow is false for panels thats why the focus is cut off

**Comment by rjahn** [comment] 2024-03-28 13:09
But it shouldn't in general.

Only for: ScrollPanel, TabsetPanel, SplitPanel, Window/Frame

For simple Panels, the overflow should be visible.

We hade some changes in the past, looks like a wrong fix?

**Comment by gimmixAT** [comment] 2024-04-28 17:07
This seems to have changed in b741e7291e614e9cf5a62d088f1e2b062378a67b -> what was the original problem there?
In which screen can I best reproduce this issue?

**Comment by rjahn** [comment] 2024-04-29 11:38
also with Components screen -> click a radio button in the middle of the screen: Group-1 or Group-2

**Comment by gimmixAT** [comment] 2024-05-13 13:58
> also with Components screen -> click a radio button in the middle of the screen: Group-1 or Group-2

In this case the hidden overflow is actually warrented because the parent RadioButtonGroupEditor / FlowLayout has autoWrap set to false. So in case there is an overflow that should be clipped.

**Comment by rjahn** [comment] 2024-05-21 09:27
but it looks wrong from user point of view.

**Comment by gimmixAT** [comment] 2024-05-21 10:55
overflow should be visible now in RadioButtonGroupEditor

**Comment by rjahn** [comment] 2024-05-21 11:17
antoher problem: Calendar screen (user: feature):

<img width="292" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/ea2c047a-87ef-477e-b86a-63e52c26dcac">

**Comment by gimmixAT** [comment] 2024-05-31 11:59
the focus render glitch on the Calendar screen should be fixed now as well

**Comment by rjahn** [comment] 2024-05-31 12:03
Great. Is this fix a general fix or should we check other editors as well because it's a very specific fix for this component?

**Closed** 2024-05-31 13:26 UTC
Labels: awaiting Feedback, Priority
